### ISSUE TITLE
Add image uploads?

### ISSUE THREAD

**Issue by arxenix** [rycus86/ghost-client#1]
Ghost has the API endpoint /uploads/ to upload an image file to the content directory. Would be great if you added support for this :)

**Comment by rycus86** [comment]
It's a very good suggestion, thanks!
I haven't seen the endpoint in the API documentation, but I'll have another look.
Do you have a reference to it's documentation by any chance?

**Comment by rycus86** [comment]
Hi @arxenix ,

Thanks again for the suggestion!
https://github.com/rycus86/ghost-client/commit/2bc88af9532980125aeb21ddcfa497f120b8d510 is implementing it:

```python
ghost.upload(file_obj=open('sample.png', 'rb'))
ghost.upload(file_path='/path/to/image.jpeg', 'rb')
ghost.upload(name='image.gif', data=open('local.gif', 'rb').read())
```

It's also in the `0.0.3` version on PyPI.
Enjoy! ;)
