### ISSUE TITLE
Create post

### ISSUE THREAD

**Issue by aburkov** [rycus86/ghost-client#4]
Hi! Ghost's API (https://api.ghost.org) doesn't support post creation. How does your client do that?

Another question: I have a custom blog, post pages are HTML and contain graphics. I would like to migrate to Ghost. Is it possible to do using your API client?

Thank you!

**Comment by rycus86** [comment]
Hi!

Thanks for your interest in this project!
Yes, the endpoint is not officially supported, but it is the one the admin UI uses when you create new posts. It was a bit of experimentation, but seems to have worked all right with the Ghost version I was developing against. If it doesn't work with the recent changes, let me know and I'll try to have a look!

As for the migration, Ghost has now switched to the new Koenig editor, that might things somewhat easier, though I haven't tried it yet. In the previous version, the posts use Markdown, which *should* accept HTML as-is. If I were you, I'd try running a Ghost locally, perhaps [in Docker](https://hub.docker.com/r/_/ghost/) so you can easily drop it and restart as a fresh installation, then test your migration against that. This way it would be low cost and effort.

Hope this helps! Let me know if you have any more questions!
