### ISSUE TITLE
Support api v2

### ISSUE THREAD

**Issue by vmarkovtsev** [rycus86/ghost-client#5]
API v0.1 does not allow to update the text of a post, for example. We need to have v2!

https://forum.ghost.org/t/python-sdk-library-unofficial/6504

**Comment by rycus86** [comment]
I had a stab at it on a branch, but I think I need a bit bigger changes as lots of endpoints have changed between v2 and before. Models seem ok, but authentication and version resolution is bit tricky.

Happy to accept PRs though! ;)

**Comment by rycus86** [comment]
Haven't really got a chance to take this forward, and I'm off Ghost now, so there's not much chance atm of getting this done anytime soon.
